name: Update Omnistrate Plan
description: "Update an Omnistrate plan with a new compose file"

inputs:
  username:
    description: "The username to use for authentication"
    required: true
  password:
    description: "The password to use for authentication"
    required: true
  file:
    description: "The file to update the plan with"
    required: true
  service-name:
    description: "The name of the service to update"
    required: true
  environment:
    description: "The environment to update the plan with"
    required: true
  environment-type:
    description: "The type of environment to update the plan with"
    required: true

runs:
  using: docker
  image: ghcr.io/omnistrate/ctl:latest
  entrypoint: /bin/sh
  args:
    - -c
    - "ls -lar && /usr/local/bin/omnistrate-ctl login --email ${{ inputs.username }} --password ${{ inputs.password }} && /usr/local/bin/omnistrate-ctl build -f /github/workspace/${{ inputs.file }} -n '${{ inputs.service-name }}' --environment '${{ inputs.environment }}' --environment-type '${{ inputs.environment-type }}' --release-as-preferred"