# Define a Docker Compose for a FalkorDB deployment with 2 replicas and 3 sentinels
version: '3.8'

services:
  node:
    image: falkordb/falkordb-node:latest
    environment:
      - RUN_NODE=1
      - RUN_SENTINEL=1
      - SENTINEL_HOST=sentinel
      - SENTINEL_PORT=26379
      - MASTER_NAME=master
    ports:
      - 6379
    networks:
      - falkordb

  sentinel:
    image: falkordb/falkordb-node:latest
    environment:
      - RUN_NODE=0
      - RUN_SENTINEL=1
      - MASTER_HOST=172.21.0.3
      - MASTER_PORT=6379
    ports:
      - 26379
    networks:
      - falkordb

networks:
  falkordb:
    driver: bridge
