# Define a Docker Compose for a FalkorDB deployment with 2 replicas and 3 sentinels
version: '3.8'

services:
  master:
    build: ./falkordb-replica
    environment:
      - IS_MASTER=1
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REPLICA_PORT=${REDIS_PORT}
    volumes:
      - $PWD/data:/data
    ports:
      - ${REDIS_PORT}
    networks:
      - falkordb

  replica:
    build: ./falkordb-replica
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - MASTER_NAME=master
      - MASTER_PORT=${REDIS_PORT}
    volumes:
      - $PWD/data:/data
    ports:
      - ${REDIS_PORT}
    networks:
      - falkordb

  sentinel:
    build: ./sentinel
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - MASTER_NAME=master
      - MASTER_PORT=${REDIS_PORT}
    ports:
      - 26379
    networks:
      - falkordb


networks:
  falkordb:
    driver: bridge