version: "3.9"

x-omnistrate-service-plan:
  name: "FalkorDB Cluster"
  tenancyType: "OMNISTRATE_DEDICATED_TENANCY"
  deployment:
    hostedDeployment:
      GcpProjectId: app-plane-dev-f7a2434f
      GcpProjectNumber: "747498641488"
      GcpServiceAccountEmail: omni-btstrp-org-q9h5kjuc0n@app-plane-dev-f7a2434f.iam.gserviceaccount.com

services:
  Cluster:
    x-omnistrate-mode-internal: false
    image: omnistrate/noop
    x-omnistrate-api-params:
      - key: name
        description: Name
        name: Name
        type: String
        modifiable: true
        required: false
        defaultValue: My favorite database
        export: true
      - key: description
        description: Description
        name: Description
        type: String
        modifiable: true
        required: false
        defaultValue: Description
        export: true
      - key: nodeInstanceType
        description: The size of the node instance. Check the documentation for more information.
        name: Node Instance Type
        type: String
        modifiable: false
        required: true
        export: true
        defaultValue: e2-custom-4-8192
        options:
          - e2-custom-4-8192
          - e2-custom-8-16384
          - e2-custom-16-32768
          - e2-custom-32-65536
        parameterDependencyMap:
          cluster-sz: nodeInstanceType
      - key: enableTLS
        description: Whether to enable TLS for the database
        name: Enable TLS
        type: Boolean
        modifiable: false
        required: true
        export: true
        defaultValue: "false"
        parameterDependencyMap:
          cluster-sz: enableTLS
      - key: falkordbUser
        description: Choose a default username for your database
        name: FalkorDB User
        type: String
        modifiable: false
        required: true
        export: true
        defaultValue: "falkordb"
        parameterDependencyMap:
          cluster-sz: falkordbUser
      - key: falkordbPassword
        description: Choose a default password for your database
        name: FalkorDB Password
        type: Password
        modifiable: false
        required: true
        export: false
        parameterDependencyMap:
          cluster-sz: falkordbPassword
      - key: RDBPersistenceConfig
        description: How often to save the RDB file to disk. Check the documentation for more information.
        name: RDB Persistence Config
        type: String
        modifiable: false
        required: false
        export: true
        defaultValue: "low"
        options:
          - "low"
          - "medium"
          - "high"
        parameterDependencyMap:
          cluster-sz: RDBPersistenceConfig
      - key: AOFPersistenceConfig
        description: Whether to enable AOF persistence. Check the documentation for more information.
        name: AOF Persistence Config
        type: String
        modifiable: false
        required: false
        export: true
        defaultValue: "everysec"
        options:
          - "everysec"
          - "always"
        parameterDependencyMap:
          cluster-sz: AOFPersistenceConfig
      - key: hostCount
        description: The number of hosts in the cluster. Each shard contains one master and one replica, so 6 hosts will create 3 shards.
        name: Host Count
        type: Float64
        modifiable: true
        required: true
        export: true
        defaultValue: '6'
        min: 6
        parameterDependencyMap:
          cluster-sz: hostCount
      - key: clusterReplicas
        description: The number of replicas per shard
        name: Cluster Replicas
        type: Float64
        modifiable: true
        required: true
        export: true
        defaultValue: '1'
        min: 1
        max: 3
        parameterDependencyMap:
          cluster-sz: clusterReplicas
    x-omnistrate-capabilities:
      backupConfiguration:
        backupRetentionInDays: 7
        backupPeriodInHours: 12
    depends_on:
      - cluster-sz

  cluster-sz:
    x-omnistrate-mode-internal: true
    image: dudizimber/falkordb-cluster:0.0.12
    x-omnistrate-compute:
      replicaCountAPIParam: hostCount
      instanceTypes:
        - cloudProvider: gcp
          apiParam: nodeInstanceType
    x-omnistrate-api-params:
      - key: hostCount
        description: The number of hosts in the cluster
        name: Host Count
        type: Float64
        modifiable: true
        required: true
        export: true
        defaultValue: '6'
        min: 6
      - key: clusterReplicas
        description: The number of replicas per shard
        name: Cluster Replicas
        type: Float64
        modifiable: true
        required: true
        export: true
        defaultValue: '1'
        min: 1
        max: 3
      - key: nodeInstanceType
        description: The size of the node instance. Check the documentation for more information.
        name: Node Instance Type
        type: String
        modifiable: false
        required: true
        export: true
        defaultValue: e2-custom-4-8192
        options:
          - e2-custom-4-8192
          - e2-custom-8-16384
          - e2-custom-16-32768
          - e2-custom-32-65536
      - key: enableTLS
        description: Whether to enable TLS for the database
        name: Enable TLS
        type: Boolean
        modifiable: false
        required: true
        export: true
        defaultValue: "false"
      - key: falkordbUser
        description: Choose a default username for your database
        name: FalkorDB User
        type: String
        modifiable: false
        required: true
        export: true
        defaultValue: "falkordb"
      - key: falkordbPassword
        description: Choose a default password for your database
        name: FalkorDB Password
        type: Password
        modifiable: false
        required: true
        export: false
      - key: RDBPersistenceConfig
        description: How often to save the RDB file to disk. Check the documentation for more information.
        name: RDB Persistence Config
        type: String
        modifiable: false
        required: false
        export: true
        defaultValue: "low"
        options:
          - "low"
          - "medium"
          - "high"
      - key: AOFPersistenceConfig
        description: Whether to enable AOF persistence. Check the documentation for more information.
        name: AOF Persistence Config
        type: String
        modifiable: false
        required: false
        export: true
        defaultValue: "everysec"
        options:
          - "everysec"
          - "always"
    volumes:
      - source: ./data
        target: /data
        type: bind
        x-omnistrate-storage:
          gcp:
            instanceStorageType: GCP::PD_BALANCED
            instanceStorageSizeGi: 200
    environment:
      - RUN_NODE=1
      - RUN_METRICS=1
      - RUN_HEALTH_CHECK=1
      - BROWSER=0
      - NODE_HOST=$sys.network.node.externalEndpoint
      - TLS=$var.enableTLS
      - FALKORDB_USER=$var.falkordbUser
      - FALKORDB_PASSWORD=$var.falkordbPassword
      - ADMIN_PASSWORD=$func.random(string, 16)
      - DATA_DIR=/data
      - INSTANCE_TYPE=$var.nodeInstanceType
      - ROOT_CA_PATH=/etc/ssl/certs/GlobalSign_Root_CA.pem
      - PERSISTENCE_RDB_CONFIG_INPUT=$var.RDBPersistenceConfig
      - PERSISTENCE_AOF_CONFIG=$var.AOFPersistenceConfig
      - HOST_COUNT=$var.hostCount
      - CLUSTER_REPLICAS=$var.clusterReplicas
      - DEBUG=1
    ports:
      - "6379"
      - "16379"
    x-omnistrate-capabilities:
      enableMultiZone: false
      enableEndpointPerReplica: true
