version: "3.9"

services:
  FalkorDB:
    x-omnistrate-mode-internal: false
    image: omnistrate/noop
    x-omnistrate-api-params:
      - key: nodeInstanceType
        description: Node Instance Type
        name: Node Instance Type
        type: String
        modifiable: false
        required: true
        export: true
        defaultValue: e2-medium
        options:
          - e2-small
          - e2-medium
        parameterDependencyMap:
          node: nodeInstanceType
      - key: numReplicas
        description: Number of Replicas
        name: Number of Replicas
        type: Float64
        modifiable: true
        required: false
        export: true
        defaultValue: "1"
        limits:
          min: 0
          max: 10
        parameterDependencyMap:
          node: numReplicas
      - key: sentinelInstanceType
        description: Sentinel Instance Type
        name: Sentinel Instance Type
        type: String
        modifiable: false
        required: true
        export: true
        defaultValue: e2-medium
        options:
          - e2-small
          - e2-medium
        parameterDependencyMap:
          node: sentinelInstanceType
          sentinel: sentinelInstanceType
      - key: sentinelOnlyReplicas
        description: Number of Sentinel-only Replicas
        name: Number of Sentinel-Only Replicas
        type: Float64
        modifiable: true
        required: true
        export: true
        defaultValue: "1"
        limits:
          min: 0
          max: 1
        parameterDependencyMap:
          node: sentinelOnlyReplicas
          sentinel: sentinelOnlyReplicas
    depends_on:
      - node
      - sentinel

  node:
    x-omnistrate-mode-internal: true
    image: falkordb/falkordb-node:latest
    x-omnistrate-compute:
      replicaCountAPIParam: numReplicas
      instanceTypes:
        - cloudProvider: aws
          apiParam: nodeInstanceType
        - cloudProvider: gcp
          apiParam: nodeInstanceType
    x-omnistrate-api-params:
      - key: nodeInstanceType
        description: Node Instance Type
        name: Node Instance Type
        type: String
        modifiable: false
        required: true
        export: true
        defaultValue: e2-medium
        options:
          - e2-small
          - e2-medium
      - key: numReplicas
        description: Number of Replicas
        name: Number of Replicas
        type: Float64
        modifiable: true
        required: false
        export: true
        defaultValue: "1"
        limits:
          min: 0
          max: 10
      - key: sentinelInstanceType
        description: Sentinel Instance Type
        name: Sentinel Instance Type
        type: String
        modifiable: false
        required: true
        export: true
        defaultValue: e2-medium
        options:
          - e2-small
          - e2-medium
        parameterDependencyMap:
          sentinel: sentinelInstanceType
      - key: sentinelOnlyReplicas
        description: Number of Sentinel-only Replicas
        name: Number of Sentinel-Only Replicas
        type: Float64
        modifiable: true
        required: true
        export: true
        defaultValue: "1"
        limits:
          min: 0
          max: 1
        parameterDependencyMap:
          sentinel: sentinelOnlyReplicas
    environment:
      - RUN_NODE=1
      - RUN_SENTINEL=1
      - SENTINEL_HOST=$sentinel.sys.network.externalClusterEndpoint
      - NODE_HOST=$sys.network.node.externalEndpoint
      - NODE_PORT=6379
      - SECURITY_CONTEXT_USER_ID=0
      - SECURITY_CONTEXT_GROUP_ID=0
      - SECURITY_CONTEXT_FS_GROUP=0
    ports:
      - "6379:6379"
      - "26379:26379"
    x-omnistrate-capabilities:
      enableMultiZone: true
      enableEndpointPerReplica: true
    depends_on:
      - sentinel


  sentinel:
    x-omnistrate-mode-internal: true
    image: falkordb/falkordb-node:latest
    x-omnistrate-compute:
      replicaCountAPIParam: sentinelOnlyReplicas
      instanceTypes:
        - cloudProvider: aws
          apiParam: sentinelInstanceType
        - cloudProvider: gcp
          apiParam: sentinelInstanceType
    environment:
      - RUN_NODE=0
      - RUN_SENTINEL=1
      - SENTINEL_PORT=26379
      - SECURITY_CONTEXT_USER_ID=0
      - SECURITY_CONTEXT_GROUP_ID=0
      - SECURITY_CONTEXT_FS_GROUP=0
    ports:
      - "26379:26379"
    x-omnistrate-api-params:
      - key: sentinelInstanceType
        description: Sentinel Instance Type
        name: Sentinel Instance Type
        type: String
        modifiable: false
        required: true
        export: true
        defaultValue: e2-medium
        options:
          - e2-small
          - e2-medium
      - key: sentinelOnlyReplicas
        description: Number of Sentinel-only Replicas
        name: Number of Sentinel-Only Replicas
        type: Float64
        modifiable: true
        required: true
        export: true
        defaultValue: "1"
        limits:
          min: 0
          max: 1
    x-omnistrate-capabilities:
      enableMultiZone: true
