version: "3.9"

services:
  FalkorDB:
    x-omnistrate-mode-internal: false
    image: omnistrate/noop
    x-omnistrate-api-params:
      - key: name
        description: Name
        name: Name
        type: String
        modifiable: true
        required: false
        defaultValue: FalkorDB Instance
        export: true
      - key: description
        description: Description
        name: Description
        type: String
        modifiable: true
        required: false
        defaultValue: FalkorDB Instance
        export: true
      - key: enableTLS
        description: Enable TLS
        name: Enable TLS
        type: Boolean
        modifiable: false
        required: true
        export: true
        defaultValue: "false"
        parameterDependencyMap:
          node: enableTLS
      - key: falkordbPassword
        description: FalkorDB Password
        name: FalkorDB Password
        type: String
        modifiable: false
        required: true
        export: false
        parameterDependencyMap:
          node: falkordbPassword
    depends_on:
      - node

  node:
    x-omnistrate-mode-internal: true
    image: falkordb/falkordb-node:v0.0.15
    x-omnistrate-compute:
      replicaCount: 1
      instanceTypes:
        - cloudProvider: gcp
          name: e2-custom-small-1024
    x-omnistrate-api-params:
      - key: enableTLS
        description: Enable TLS
        name: Enable TLS
        type: Boolean
        modifiable: false
        required: true
        export: true
        defaultValue: "false"
      - key: falkordbPassword
        description: FalkorDB Password
        name: FalkorDB Password
        type: String
        modifiable: false
        required: true
        export: false
    volumes:
      - ./data:/data
    environment:
      - RUN_NODE=1
      - RUN_SENTINEL=1
      - NODE_HOST=$sys.network.node.externalEndpoint
      - NODE_PORT=6379
      - RUN_METRICS=1
      - TLS=$var.enableTLS
      - FALKORDB_PASSWORD=$var.falkordbPassword
      - ADMIN_PASSWORD=$func.random(string, 16)
      - DATA_DIR=/data
      - SECURITY_CONTEXT_USER_ID=0
      - SECURITY_CONTEXT_GROUP_ID=0
      - SECURITY_CONTEXT_FS_GROUP=0
    ports:
      - "6379:6379"
      - "9121:9121"
    x-omnistrate-capabilities:
      enableMultiZone: false
      enableEndpointPerReplica: true
    x-omnistrate-storage:
      gcp:
        instanceStorageType: GCP::PD_BALANCED
        instanceStorageSizeGi: 10
