version: "3.9"

services:
  FalkorDB:
    x-omnistrate-mode-internal: false
    image: omnistrate/noop
    x-omnistrate-api-params:
      - key: name
        description: Name
        name: Name
        type: String
        modifiable: true
        required: false
        defaultValue: FalkorDB Instance
        export: true
      - key: description
        description: Description
        name: Description
        type: String
        modifiable: true
        required: false
        defaultValue: FalkorDB Instance
        export: true
      - key: nodeInstanceType
        description: Node Instance Type
        name: Node Instance Type
        type: String
        modifiable: false
        required: true
        export: true
        defaultValue: e2-medium
        options:
          - e2-small
          - e2-medium
          - e2-custom-2-6144
          - e2-custom-4-10240
          - e2-custom-8-18432
          - e2-custom-16-34816
        parameterDependencyMap:
          node: nodeInstanceType
      - key: numReplicas
        description: Number of Replicas
        name: Number of Replicas
        type: Float64
        modifiable: true
        required: false
        export: true
        defaultValue: "1"
        limits:
          min: 0
          max: 10
        parameterDependencyMap:
          node: numReplicas
      - key: enableTLS
        description: Enable TLS
        name: Enable TLS
        type: Boolean
        modifiable: false
        required: true
        export: true
        defaultValue: "false"
        parameterDependencyMap:
          node: enableTLS
      - key: falkordbPassword
        description: FalkorDB Password
        name: FalkorDB Password
        type: String
        modifiable: false
        required: true
        export: false
        parameterDependencyMap:
          node: falkordbPassword
      - key: storageSize
        description: Minimum 10Gi (10). Recommended to be at least 2x the size of the data set.
        name: Disk Size (in Gi)
        type: String
        defaultValue: "10"
        modifiable: false
        required: true
        export: true
        options:
          - "10"
          - "20"
          - "30"
          - "40"
          - "50"
          - "60"
          - "70"
          - "80"
          - "90"
          - "100"
        parameterDependencyMap:
          node: storageSize
    depends_on:
      - node

  node:
    x-omnistrate-mode-internal: true
    image: falkordb/falkordb-node:v0.0.15
    x-omnistrate-compute:
      replicaCountAPIParam: numReplicas
      instanceTypes:
        - cloudProvider: gcp
          apiParam: nodeInstanceType
    x-omnistrate-api-params:
      - key: nodeInstanceType
        description: Node Instance Type
        name: Node Instance Type
        type: String
        modifiable: false
        required: true
        export: true
        defaultValue: e2-medium
        options:
          - e2-small
          - e2-medium
          - e2-custom-2-6144
          - e2-custom-4-10240
          - e2-custom-8-18432
          - e2-custom-16-34816
      - key: numReplicas
        description: Number of Replicas
        name: Number of Replicas
        type: Float64
        modifiable: true
        required: false
        export: true
        defaultValue: "1"
        limits:
          min: 0
          max: 10
      - key: enableTLS
        description: Enable TLS
        name: Enable TLS
        type: Boolean
        modifiable: false
        required: true
        export: true
        defaultValue: "false"
        parameterDependencyMap:
          sentinel: enableTLS
      - key: falkordbPassword
        description: FalkorDB Password
        name: FalkorDB Password
        type: String
        modifiable: false
        required: true
        export: false
        parameterDependencyMap:
          sentinel: falkordbPassword
      - key: storageSize
        description: Minimum 10Gi (10). Recommended to be at least 2x the size of the data set.
        name: Disk Size (in Gi)
        type: String
        defaultValue: "10"
        modifiable: false
        required: true
        export: true
        options:
          - "10"
          - "20"
          - "30"
          - "40"
          - "50"
          - "60"
          - "70"
          - "80"
          - "90"
          - "100"
    volumes:
      - ./data:/data
    environment:
      - RUN_NODE=1
      - RUN_SENTINEL=1
      - RUN_METRICS=1
      - RUN_HEALTH_CHECK=1
      - SENTINEL_HOST=$sentinel.sys.network.externalClusterEndpoint
      - NODE_HOST=$sys.network.node.externalEndpoint
      - NODE_PORT=6379
      - TLS=$var.enableTLS
      - FALKORDB_PASSWORD=$var.falkordbPassword
      - ADMIN_PASSWORD=$func.random(string, 16)
      - DATA_DIR=/data
      - SECURITY_CONTEXT_USER_ID=0
      - SECURITY_CONTEXT_GROUP_ID=0
      - SECURITY_CONTEXT_FS_GROUP=0
    ports:
      - "6379:6379"
      - "26379:26379"
      - "9121:9121"
    x-omnistrate-capabilities:
      enableMultiZone: false
      enableEndpointPerReplica: true
    x-omnistrate-storage:
      gcp:
        instanceStorageType: GCP::PD_BALANCED
        instanceStorageSizeGiAPIParam: storageSize
    x-omnistrate-actionhooks:
      - scope: NODE
        type: HEALTH_CHECK
        commandTemplate: >
          #!/bin/bash

          HEALTH_CHECK_URL="${HEALTH_CHECK_HOST:-localhost}:${HEALTH_CHECK_PORT:-8081}/healthcheck"

          call_health_check() {

            echo "Health check URL: $HEALTH_CHECK_URL"
            curl -sf $HEALTH_CHECK_URL
            
            if [ $? -ne 0 ]; then
              echo "Health check failed"
              exit 1
            fi
          }

          call_health_check
    depends_on:
      - sentinel


  sentinel:
    x-omnistrate-mode-internal: true
    image: falkordb/falkordb-node:v0.0.15
    x-omnistrate-compute:
      replicaCount: 1
      instanceTypes:
        - cloudProvider: gcp
          name: e2-small
    environment:
      - RUN_NODE=0
      - RUN_SENTINEL=1
      - RUN_METRICS=0
      - SENTINEL_PORT=26379
      - TLS=$var.enableTLS
      - FALKORDB_PASSWORD=$var.falkordbPassword
      - ADMIN_PASSWORD=rZyD2N7UsFwzkb
      - SECURITY_CONTEXT_USER_ID=0
      - SECURITY_CONTEXT_GROUP_ID=0
      - SECURITY_CONTEXT_FS_GROUP=0
    ports:
      - "26379:26379"
    x-omnistrate-capabilities:
      enableMultiZone: false
      enableEndpointPerReplica: true
    x-omnistrate-api-params:
      - key: enableTLS
        description: Enable TLS
        name: Enable TLS
        type: Boolean
        modifiable: false
        required: true
        export: true
        defaultValue: "false"
      - key: falkordbPassword
        description: FalkorDB Password
        name: FalkorDB Password
        type: String
        modifiable: false
        required: true
        export: false
