{
 "title": "FalkorDB Dashboard",
 "description": "FalkorDB Dashboard",
 "tags": [ "prometheus" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(___customer_redis_uptime_in_seconds, namespace)"
   },
   {
    "name": "pod",
    "query": "label_values(___customer_redis_uptime_in_seconds{namespace=~\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Max Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(___customer_redis_uptime_in_seconds{pod=~\"$pod\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(___customer_redis_connected_clients{pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(100 * sum(___customer_redis_memory_used_bytes{pod=~\"$pod\"})  / sum(___customer_redis_memory_max_bytes{pod=~\"$pod\"}))"
    }
   ]
  },
  {
   "title": "Total Commands / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(___customer_redis_commands_total{pod=~\"$pod\"} [1m])) by (cmd)",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "___customer_redis_memory_used_bytes{pod=~\"$pod\"}",
     "legendFormat": "used, {{ pod }}"
    },
    {
     "expr": "___customer_redis_memory_max_bytes{pod=~\"$pod\"}",
     "legendFormat": "max, {{ pod }}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(___customer_redis_net_input_bytes_total{pod=~\"$pod\"}[5m]))",
     "legendFormat": "{{ input }}"
    },
    {
     "expr": "sum(rate(___customer_redis_net_output_bytes_total{pod=~\"$pod\"}[5m]))",
     "legendFormat": "{{ output }}"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (___customer_redis_db_keys{pod=~\"$pod\"}) by (db, pod)",
     "legendFormat": "{{ db }}, {{ pod }}"
    }
   ]
  },
  {
   "title": "Connected/Blocked Clients",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(___customer_redis_connected_clients{pod=~\"$pod\"})",
     "legendFormat": "connected"
    },
    {
     "expr": "sum(___customer_redis_blocked_clients{pod=~\"$pod\"})",
     "legendFormat": "blocked"
    }
   ]
  },
  {
   "title": "Average Time Spent by Command / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(irate(___customer_redis_commands_duration_seconds_total{pod =~ \"$pod\"}[1m])) by (cmd)\n  /\nsum(irate(___customer_redis_commands_total{pod =~ \"$pod\"}[1m])) by (cmd)\n",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Total Time Spent by Command / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(irate(___customer_redis_commands_duration_seconds_total{pod=~\"$pod\"}[1m])) by (cmd) != 0",
     "legendFormat": "{{ cmd }}"
    }
   ]
  }
 ]
}