name: Create Omnistrate Custom Network
description: "Create a custom network in Omnistrate"

inputs:
  username:
    description: "The username to use for authentication"
    required: true
  password:
    description: "The password to use for authentication"
    required: true
  cloud_provider:
    description: "The cloud provider to use for the custom network"
    required: true
  region:
    description: "The region to use for the custom network"
    required: true
  cidr:
    description: "The CIDR to use for the custom network"
    required: true
  name:
    description: "The name to use for the custom network"
    required: true

runs:
  using: docker
  image: ghcr.io/omnistrate/ctl:latest
  entrypoint: /bin/sh
  args:
    - -c
    - "/usr/local/bin/omnistrate-ctl login --email ${{ inputs.username }} --password ${{ inputs.password }} && /usr/local/bin/omnistrate-ctl custom-network list -o json | grep -q '${{ inputs.name }}' || /usr/local/bin/omnistrate-ctl custom-network create --cloud-provider ${{ inputs.cloud_provider }} --region ${{ inputs.region }} --cidr ${{ inputs.cidr }} --name '${{ inputs.name }}'"
