apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  namespace: observability-test
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s

    storage:
      tsdb:
        out_of_order_time_window: 24h

    scrape_configs:

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-server
  namespace: observability-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: prometheus
      containers:
        - name: prometheus
          image: prom/prometheus
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-server-conf
              mountPath: /etc/prometheus
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --web.enable-remote-write-receiver

      volumes:
        - name: prometheus-server-conf
          configMap:
            name: prometheus-server-conf
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
  namespace: observability-test
spec:
  selector:
    app: prometheus-server
  ports:
    - port: 9090
      targetPort: 9090
  type: ClusterIP
