apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: fluentbit-monitor
spec:
  podMetricsEndpoints:
    - bearerTokenSecret:
        key: ""
        name: ""
      port: metrics
  selector:
    matchLabels:
      component: fluentbit-gke
  namespaceSelector:
    any: true
