name: Delete Omnistrate Custom Network
description: "Delete a custom network in Omnistrate"

inputs:
  username:
    description: "The username to use for authentication"
    required: true
  password:
    description: "The password to use for authentication"
    required: true
  custom_network_name:
    description: "The name of the custom network"

runs:
  using: docker
  image: ghcr.io/omnistrate/ctl:latest
  entrypoint: /bin/sh
  args:
    - -c
    - "/usr/local/bin/omnistrate-ctl login --email ${{ inputs.username }} --password ${{ inputs.password }} && /usr/local/bin/omnistrate-ctl custom-network delete ${{ inputs.custom_network_name }}"
