name: Delete Omnistrate Custom Network
description: "Delete a custom network in Omnistrate"

inputs:
  username:
    description: "The username to use for authentication (unused, kept for compatibility)"
    required: false
  password:
    description: "The API key to use for authentication"
    required: true
  custom_network_name:
    description: "The name of the custom network"

runs:
  using: docker
  image: ghcr.io/omnistrate/ctl:0.11.3
  entrypoint: /bin/sh
  args:
    - -c
    - "echo '${{ inputs.password }}' | /usr/local/bin/omnistrate-ctl login --api-key-stdin && /usr/local/bin/omnistrate-ctl custom-network delete ${{ inputs.custom_network_name }}"
