version: "3.9"

x-omnistrate-service-plan:
  name: "FalkorDB Startup"
  tenancyType: "OMNISTRATE_MULTI_TENANCY"
  deployment:
    hostedDeployment:
      GcpProjectId: "$GcpProjectId"
      GcpProjectNumber: "$GcpProjectNumber"
      GcpServiceAccountEmail: "$GcpServiceAccountEmail"
      AwsAccountId: "$AwsAccountId"
      AwsBootstrapRoleAccountArn: "$AwsBootstrapRoleAccountArn"
  metering:
    gcsBucketName: $MeteringBucketName
  validPaymentMethodRequired: true
  maxNumberOfInstancesAllowed: 10
  billingProductID: "startup"
  pricing:
    - dimension: memory
      unit: GiB
      timeUnit: hour
      price: 0.1
x-pre-upgrade-hook: &preupgradehook
  commandTemplate: |
    #!/usr/bin/env bash
    set -euo pipefail
    echo "Running BGREWRITEAOF before upgrade"

    adminpass=$(curl -s   --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt   -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)"   https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT/api/v1/namespaces/$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)/secrets | grep '.*adminpassword.*"$' | awk 'NR==1{print $2}' | base64 -d)
    if [[ -z "$adminpass" ]]; then
        echo "ERROR: Failed to retrieve admin password from secret. Cannot proceed with Redis operations." >&2
        exit 1
    fi
    readonly NODE_PORT="${NODE_PORT:-6379}"

    # Build redis-cli options safely
    REDIS_OPTS=(
      --no-auth-warning
      -a "$adminpass"
    )

    # Add TLS flag if enabled
    [[ "${TLS:-false}" == "true" ]] && REDIS_OPTS+=(--tls)

    # Add the actual command at the end
    REDIS_OPTS+=(BGREWRITEAOF)

    execute_bgrewriteaof() {
      local node_host=$1

      echo "Executing BGREWRITEAOF on $node_host"
      
      redis-cli -h "$node_host" -p "$NODE_PORT" "${REDIS_OPTS[@]}"
      
      # Wait for AOF rewrite to complete
      echo "Waiting for AOF rewrite to complete on $node_host..."
      local max_wait=300  # Maximum wait time in seconds (5 minutes)
      local elapsed=0
      local check_interval=2
      
      while [ $elapsed -lt $max_wait ]; do
        local aof_status=$(redis-cli -h "$node_host" -p "$NODE_PORT" "${REDIS_OPTS[@]:0:${#REDIS_OPTS[@]}-1}" INFO persistence | grep "aof_rewrite_in_progress" | cut -d: -f2 | tr -d '\r')
        
        if [ "$aof_status" == "0" ]; then
          echo "AOF rewrite completed on $node_host"
          return 0
        fi
        
        sleep $check_interval
        elapsed=$((elapsed + check_interval))
        echo "Still waiting... (${elapsed}s elapsed)"
      done
      
      echo "Warning: AOF rewrite did not complete within ${max_wait}s on $node_host"
    }

    run_for_range() {
      local prefix=$1
      local count=$2

      for ((i = 0; i < count; i++)); do
        execute_bgrewriteaof "${prefix}-${i}"
      done
    }

    case "$RESOURCE_ALIAS" in
      node-s)
        execute_bgrewriteaof "node-s-0"
        ;;

      node-mz)
        run_for_range "node-mz" "${NUM_REPLICAS}"
        ;;

      node-sz)
        run_for_range "node-sz" "${NUM_REPLICAS}"
        ;;

      cluster-mz)
        run_for_range "cluster-mz" 6
        ;;

      cluster-sz)
        run_for_range "cluster-sz" 6
        ;;

      *)
        echo "Unknown RESOURCE_ALIAS: $RESOURCE_ALIAS"
        exit 1
        ;;
    esac
services:
  # Standalone

  Standalone:
    x-omnistrate-mode-internal: false
    image: omnistrate/noop
    x-omnistrate-api-params:
      - key: name
        description: Name
        name: Name
        type: String
        modifiable: true
        required: false
        defaultValue: My favorite database
        export: true
      - key: description
        description: Description
        name: Description
        type: String
        modifiable: true
        required: false
        defaultValue: Description
        export: true
      - key: enableTLS
        description: Whether to enable TLS for the database
        name: Enable TLS
        type: Boolean
        modifiable: false
        required: true
        export: true
        defaultValue: "false"
        parameterDependencyMap:
          node-s: enableTLS
      - key: falkordbUser
        description: Choose a default username for your database
        name: FalkorDB User
        type: String
        modifiable: false
        required: true
        export: true
        defaultValue: "falkordb"
        parameterDependencyMap:
          node-s: falkordbUser
      - key: falkordbPassword
        description: Choose a default password for your database. Updating this value after deployment will restart the instance.
        name: FalkorDB Password
        type: Password
        modifiable: true
        required: true
        export: false
        parameterDependencyMap:
          node-s: falkordbPassword
      - key: RDBPersistenceConfig
        description: How often to save the RDB file to disk. Check the documentation for more information.
        name: RDB Persistence Config
        type: String
        modifiable: false
        required: false
        export: true
        defaultValue: "low"
        options:
          - "low"
          - "medium"
          - "high"
        parameterDependencyMap:
          node-s: RDBPersistenceConfig
      - key: AOFPersistenceConfig
        description: Whether to enable AOF persistence. Check the documentation for more information.
        name: AOF Persistence Config
        type: String
        modifiable: false
        required: false
        export: true
        defaultValue: "everysec"
        options:
          - "everysec"
          - "always"
        parameterDependencyMap:
          node-s: AOFPersistenceConfig

      - key: falkorDBCacheSize
        description: Choose the cache size for your database
        name: FalkorDB Cache Size
        type: Float64
        modifiable: false
        required: false
        export: true
        defaultValue: "25"
        limits:
          min: 1
          max:  256
        parameterDependencyMap:
          node-s: falkorDBCacheSize
      - key: falkorDBNodeCreationBuffer
        description: Choose the buffer size for your database
        name: FalkorDB Node Creation Buffer
        type: Float64
        modifiable: false
        required: false
        export: true
        defaultValue: "16384"
        limits:
          min: 256
          max:  32768
        parameterDependencyMap:
          node-s: falkorDBNodeCreationBuffer
      - key: falkorDBMaxQueuedQueries
        description: Choose the max queued queries for your database
        name: FalkorDB Max Queued Queries
        type: Float64
        modifiable: false
        required: false
        export: true
        defaultValue: "50"
        limits:
          min: 1
          max:  512
        parameterDependencyMap:
          node-s: falkorDBMaxQueuedQueries
      - key: falkorDBTimeoutMax
        description: Choose the timeout max for your database
        name: FalkorDB Timeout Max
        type: Float64
        modifiable: false
        required: false
        export: true
        defaultValue: "0"
        limits:
          min: 0
          max:  45000
        parameterDependencyMap:
          node-s: falkorDBTimeoutMax
      - key: falkorDBTimeoutDefault
        description: Choose the timeout default for your database
        name: FalkorDB Timeout Default
        type: Float64
        modifiable: false
        required: false
        export: true
        defaultValue: "0"
        limits:
          min: 0
          max:  45000
        parameterDependencyMap:
          node-s: falkorDBTimeoutDefault
      - key: falkorDBResultSetSize
        description: Choose the result set size for your database
        name: FalkorDB Result Set Size
        type: Float64
        modifiable: false
        required: false
        export: true
        defaultValue: "10000"
        limits:
          min: 0
          max:  1000000
        parameterDependencyMap:
          node-s: falkorDBResultSetSize
      - key: falkorDBQueryMemCapacity
        description: Choose the query mem capacity for your database
        name: FalkorDB Query Mem Capacity
        type: Float64
        modifiable: false
        required: false
        export: true
        defaultValue: "21474836480"
        limits:
          min: 5242880
          max:  21474836480
        parameterDependencyMap:
          node-s: falkorDBQueryMemCapacity
      - key: memoryRequestsAndLimits
        description: Choose the memory amount for your database
        name: Memory
        type: String
        modifiable: false
        required: false
        export: true
        defaultValue: "1GB"
        labeledOptions:
          1GB: "1200M"
          2GB: "2200M"
        parameterDependencyMap:
          node-s: memoryRequestsAndLimits
    x-omnistrate-capabilities:
      backupConfiguration:
        backupRetentionInDays: 7
        backupPeriodInHours: 12
    depends_on:
      - node-s

  node-s:
    x-omnistrate-mode-internal: true
    image: $FalkorDBNodeImage
    x-omnistrate-compute:
      replicaCount: 1
      resourceRequestMemoryAPIParam: memoryRequestsAndLimits
      resourceRequestCPUAPIParam: resourceRequestCPU
      resourceLimitMemoryAPIParam: memoryRequestsAndLimits
      resourceLimitCPUAPIParam: resourceLimitCPU
    x-omnistrate-api-params:
      - key: enableTLS
        description: Whether to enable TLS for the database
        name: Enable TLS
        type: Boolean
        modifiable: false
        required: true
        export: true
        defaultValue: "false"
      - key: falkordbUser
        description: Choose a default username for your database
        name: FalkorDB User
        type: String
        modifiable: false
        required: true
        export: true
        defaultValue: "falkordb"
      - key: falkordbPassword
        description: Choose a default password for your database. Updating this value after deployment will restart the instance.
        name: FalkorDB Password
        type: Password
        modifiable: true
        required: true
        export: false
      - key: RDBPersistenceConfig
        description: How often to save the RDB file to disk. Check the documentation for more information.
        name: RDB Persistence Config
        type: String
        modifiable: false
        required: false
        export: true
        defaultValue: "low"
        options:
          - "low"
          - "medium"
          - "high"
      - key: AOFPersistenceConfig
        description: Whether to enable AOF persistence. Check the documentation for more information.
        name: AOF Persistence Config
        type: String
        modifiable: false
        required: false
        export: true
        defaultValue: "everysec"
        options:
          - "everysec"
          - "always"

      - key: falkorDBCacheSize
        description: Choose the cache size for your database
        name: FalkorDB Cache Size
        type: Float64
        modifiable: false
        required: false
        export: true
        defaultValue: "25"
        limits:
          min: 1
          max:  256
      - key: falkorDBNodeCreationBuffer
        description: Choose the buffer size for your database
        name: FalkorDB Node Creation Buffer
        type: Float64
        modifiable: false
        required: false
        export: true
        defaultValue: "16384"
        limits:
          min: 256
          max:  32768
      - key: falkorDBMaxQueuedQueries
        description: Choose the max queued queries for your database
        name: FalkorDB Max Queued Queries
        type: Float64
        modifiable: false
        required: false
        export: true
        defaultValue: "50"
        limits:
          min: 1
          max:  512
      - key: falkorDBTimeoutMax
        description: Choose the timeout max for your database
        name: FalkorDB Timeout Max
        type: Float64
        modifiable: false
        required: false
        export: true
        defaultValue: "0"
        limits:
          min: 0
          max:  45000
      - key: falkorDBTimeoutDefault
        description: Choose the timeout default for your database
        name: FalkorDB Timeout Default
        type: Float64
        modifiable: false
        required: false
        export: true
        defaultValue: "0"
        limits:
          min: 0
          max:  45000
      - key: falkorDBResultSetSize
        description: Choose the result set size for your database
        name: FalkorDB Result Set Size
        type: Float64
        modifiable: false
        required: false
        export: true
        defaultValue: "10000"
        limits:
          min: 0
          max:  1000000
      - key: falkorDBQueryMemCapacity
        description: Choose the query mem capacity for your database
        name: FalkorDB Query Mem Capacity
        type: Float64
        modifiable: false
        required: false
        export: true
        defaultValue: "21474836480"
        limits:
          min: 5242880
          max:  21474836480
      - key: memoryRequestsAndLimits
        description: Choose the memory amount for your database
        name: Memory
        type: String
        modifiable: false
        required: false
        export: true
        defaultValue: "1GB"
        labeledOptions:
          1GB: "1200M"
          2GB: "2200M"
      - key: resourceRequestCPU
        name: CPU Request
        description: CPU Request for the Falkordb instance
        type: String
        modifiable: false
        required: false
        export: false
        defaultValue: "0.2"
      - key: resourceLimitCPU
        name: CPU Limit
        description: CPU Limit for the Falkordb instance
        type: String
        modifiable: false
        required: false
        export: false
        defaultValue: "1"
    volumes:
      - source: ./data
        target: /data
        type: bind
        x-omnistrate-storage:
          gcp:
            instanceStorageType: GCP::PD_BALANCED
            instanceStorageSizeGi: 20
          aws:
            instanceStorageType: AWS::EBS_GP3
            instanceStorageSizeGi: 20
    secrets:
      - source: adminpasspath
        target: /run/secrets/adminpassword
      - source: falkordbpasspath
        target: /run/secrets/falkordbpassword
    environment:
      - RUN_NODE=1
      - RUN_SENTINEL=0
      - RUN_METRICS=1
      - RUN_HEALTH_CHECK=1
      - BROWSER=0
      - NODE_HOST=$sys.network.node.externalEndpoint
      - NODE_PORT=6379
      - TLS=$var.enableTLS
      - FALKORDB_USER=$var.falkordbUser
      - FALKORDB_UPGRADE_PASSWORD=$func.random(string, 16, 20)
      - DATA_DIR=/var/lib/falkordb
      - RANDOM_NODE_PORT=$sys.network.node.externalPorts["6379"]
      - MEMORY_LIMIT=$var.memoryRequestsAndLimits
      - ROOT_CA_PATH=/etc/ssl/certs/ca-certificates.crt
      - PERSISTENCE_RDB_CONFIG_INPUT=$var.RDBPersistenceConfig
      - PERSISTENCE_AOF_CONFIG=$var.AOFPersistenceConfig
      - FALKORDB_CACHE_SIZE=$var.falkorDBCacheSize
      - FALKORDB_NODE_CREATION_BUFFER=$var.falkorDBNodeCreationBuffer
      - FALKORDB_MAX_QUEUED_QUERIES=$var.falkorDBMaxQueuedQueries
      - FALKORDB_TIMEOUT_MAX=$var.falkorDBTimeoutMax
      - FALKORDB_TIMEOUT_DEFAULT=$var.falkorDBTimeoutDefault
      - FALKORDB_RESULT_SET_SIZE=$var.falkorDBResultSetSize
      - FALKORDB_QUERY_MEM_CAPACITY=$var.falkorDBQueryMemCapacity
      - SKIP_HEALTH_CHECK=false
    ports:
      - "6379:6379"
    x-omnistrate-capabilities:
      enableMultiZone: false
      enableEndpointPerReplica: true
      sidecars:
        healthcheck:
          imageNameWithTag: $FalkorDBHealthcheckImage
          resourceLimits:
            cpu: "20m"
            memory: 30Mi
        exporter:
          imageNameWithTag: $FalkorDBExporterImage
          resourceLimits:
            cpu: "50m"
            memory: 50Mi
        oom_score_patch:
          imageNameWithTag: busybox:latest
          resourceLimits:
            cpu: "20m"
            memory: "32Mi"
          securityContext:
            runAsGroup: 0
            runAsNonRoot: false
            runAsUser: 0
            capabilities:
              add:
                - SYS_RESOURCE
          command:
            [
              "sh",
              "-c",
              'while true; do for d in /proc/[0-9]*; do comm=$(cat "$d/comm" 2>/dev/null); case "$comm" in redis-server*|healthcheck*) pid=${d#/proc/}; cur=$(cat "$d/oom_score_adj" 2>/dev/null || echo); if [ "$cur" != "-1000" ]; then echo -1000 > "$d/oom_score_adj" 2>/dev/null && echo "[$(date +%FT%T%z)] set oom_score_adj=-1000 for $comm (pid $pid)"; fi ;; esac; done; sleep 1; done',
            ]
    x-omnistrate-actionhooks:
      - scope: CLUSTER
        type: PRE_UPGRADE
        <<: *preupgradehook
      - scope: NODE
        type: STARTUP_CHECK
        commandTemplate: |
          #!/bin/bash

          STARTUP_CHECK_URL="${STARTUP_CHECK_HOST:-localhost}:${STARTUP_CHECK_PORT:-8081}/startup"
          call_startup_check() {

            echo "Startup check URL: $STARTUP_CHECK_URL"
            curl -sf $STARTUP_CHECK_URL
            
            if [ $? -ne 0 ]; then
              echo "Startup check failed"
              exit 1
            fi
          }

          if [[ ! -z $RUN_HEALTH_CHECK ]] && [[ $RUN_HEALTH_CHECK -eq 1 ]];then
            call_startup_check
          fi
      - scope: NODE
        type: READINESS_CHECK
        commandTemplate: |
          #!/bin/bash

          READINESS_CHECK_URL="${READY_CHECK_HOST:-localhost}:${READY_CHECK_PORT:-8081}/readiness"
          call_readiness_check() {

            echo "Ready check URL: $READINESS_CHECK_URL"
            curl -sf $READINESS_CHECK_URL
            
            if [ $? -ne 0 ]; then
              echo "Readiness check failed"
              exit 1
            fi
          }

          if [[ ! -z $RUN_HEALTH_CHECK ]] && [[ $RUN_HEALTH_CHECK -eq 1 ]];then
            call_readiness_check
          fi

      - scope: NODE
        type: HEALTH_CHECK
        commandTemplate: |
          #!/bin/bash

          LIVENESS_CHECK_URL="${HEALTH_CHECK_HOST:-localhost}:${HEALTH_CHECK_PORT:-8081}/liveness"
          call_liveness_check() {

            echo "Health check URL: $LIVENESS_CHECK_URL"
            curl -sf $LIVENESS_CHECK_URL
            
            if [ $? -ne 0 ]; then
              echo "Health check failed"
              exit 1
            fi
          }

          if [[ ! -z $RUN_HEALTH_CHECK ]] && [[ $RUN_HEALTH_CHECK -eq 1 ]];then
          call_liveness_check
          fi

secrets:
  adminpasspath:
    file: ./secrets/adminpassword
  falkordbpasspath:
    file: ./secrets/falkordbpassword
