name: Build and test image

on:
  push:
  workflow_dispatch:

concurrency:
  group: falkordb-node-branch-${{ github.ref_name }}
  cancel-in-progress: false

env:
  IMAGE_NAME: falkordb-node
  FALKORDB_VERSION: v4.0.8

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          build-args: FALKORDB_VERSION=${{ env.FALKORDB_VERSION }}
          context: ./falkordb-node
          file: ./falkordb-node/Dockerfile
          push: true
          tags: falkordb/${{ env.IMAGE_NAME }}:dev-${{ github.event.head_commit.id }}

      - name: Notify Google Chat
        id: test-action
        if: failure() # only send notification in case of failure
        uses: SimonScholz/google-chat-action@v1.1.0
        with:
          webhookUrl: "${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}"
          jobStatus: ${{ job.status }}
          threadKey: ${{ github.job }}

  omnistrate-update-plans:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Replace Variables
        run: |
          sed -i 's/$GcpProjectId/${{ vars.GCP_PROJECT_ID }}/g' omnistrate.free.yaml
          sed -i 's/$GcpProjectNumber/${{ vars.GCP_PROJECT_NUMBER }}/g' omnistrate.free.yaml
          sed -i 's/$GcpServiceAccountEmail/${{ vars.GCP_SERVICE_ACCOUNT_EMAIL }}/g' omnistrate.free.yaml
          sed -i 's/$FalkorDBNodeImage/falkordb\/falkordb-node:dev-${{ github.event.head_commit.id }}/g' omnistrate.free.yaml
          sed -i 's/$GcpProjectId/${{ vars.GCP_PROJECT_ID }}/g' omnistrate.pro.yaml
          sed -i 's/$GcpProjectNumber/${{ vars.GCP_PROJECT_NUMBER }}/g' omnistrate.pro.yaml
          sed -i 's/$GcpServiceAccountEmail/${{ vars.GCP_SERVICE_ACCOUNT_EMAIL }}/g' omnistrate.pro.yaml
          sed -i 's/$FalkorDBNodeImage/falkordb\/falkordb-node:dev-${{ github.event.head_commit.id }}/g' omnistrate.pro.yaml

      - name: Merge omnistrate composes
        run: |
          sudo add-apt-repository ppa:rmescandon/yq 
          sudo apt update 
          sudo apt install yq -y
          yq ea '. as $item ireduce ({}; . * $item )' omnistrate.pro.yaml omnistrate.free.yaml | sed 's/FalkorDB Free/${{ github.ref_name }}/' > merged.yaml

      - name: Update Omnistrate plan
        uses: ./.github/actions/update-omnistrate-plan
        id: update_omnistrate_plan
        with:
          username: ${{ secrets.OMNISTRATE_USERNAME }}
          password: ${{ secrets.OMNISTRATE_PASSWORD }}
          file: merged.yaml
          service-name: "FalkorDB Internal"

  promote-pt-version:
    needs: omnistrate-update-plans
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./tests/requirements.txt

      - name: Promote PT version
        env:
          OMNISTRATE_SERVICE_ID: s-iBKzmR5obS
          OMNISTRATE_PRODUCT_TIER_ID: pt-vnVxCsPEcV
        run: |
          python ./tests/promote_pt_version.py ${{ secrets.OMNISTRATE_USERNAME }} ${{ secrets.OMNISTRATE_PASSWORD }} ${{ env.OMNISTRATE_SERVICE_ID }} ${{ env.OMNISTRATE_PRODUCT_TIER_ID }}

  test:
    needs: promote-pt-version
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        instances:
          - name: Free - GCP/us-central1 - Failover & Persistence
            testFile: test_free.py
            cloudProvider: gcp
            cloudRegion: us-central1
            subscriptionId: sub-GJPV3NoNC0
            apiVersion: 2022-09-01-00
            apiPath: 2022-09-01-00/resource-instance/sp-JvkxkPhinN/falkordb-internal/v1/dev/falkordb-internal-customer-hosted/falkordb-internal-hosted-tier-falkordb-internal-customer-hosted-model-omnistrate-dedicated-tenancy/free
            apiFailoverPath: 2022-09-01-00/resource-instance/sp-JvkxkPhinN/falkordb-internal/v1/dev/falkordb-internal-customer-hosted/falkordb-internal-hosted-tier-falkordb-internal-customer-hosted-model-omnistrate-dedicated-tenancy/node-f
            apiSignInPath: 2022-09-01-00/resource-instance/user/signin
            extraParams: ""
          - name: PRO/Standalone - GCP/us-central1 - Failover & Persistence
            testFile: test_standalone.py
            cloudProvider: gcp
            cloudRegion: us-central1
            subscriptionId: sub-GJPV3NoNC0
            apiPath: 2022-09-01-00/resource-instance/sp-JvkxkPhinN/falkordb-internal/v1/dev/falkordb-internal-customer-hosted/falkordb-internal-hosted-tier-falkordb-internal-customer-hosted-model-omnistrate-dedicated-tenancy/standalone
            apiFailoverPath: 2022-09-01-00/resource-instance/sp-JvkxkPhinN/falkordb-internal/v1/dev/falkordb-internal-customer-hosted/falkordb-internal-hosted-tier-falkordb-internal-customer-hosted-model-omnistrate-dedicated-tenancy/node-s
            apiSignInPath: 2022-09-01-00/resource-instance/user/signin
            # extraParams: <instance_size> <disk_size> <tls>
            extraParams: "e2-custom-4-10240 30 false"
          - name: PRO/SingleZone - GCP/us-central1 - Failover & Persistence
            testFile: test_single_zone.py
            cloudProvider: gcp
            cloudRegion: us-central1
            subscriptionId: sub-GJPV3NoNC0
            apiPath: 2022-09-01-00/resource-instance/sp-JvkxkPhinN/falkordb-internal/v1/dev/falkordb-internal-customer-hosted/falkordb-internal-hosted-tier-falkordb-internal-customer-hosted-model-omnistrate-dedicated-tenancy/single-Zone
            apiFailoverPath: 2022-09-01-00/resource-instance/sp-JvkxkPhinN/falkordb-internal/v1/dev/falkordb-internal-customer-hosted/falkordb-internal-hosted-tier-falkordb-internal-customer-hosted-model-omnistrate-dedicated-tenancy
            apiSignInPath: 2022-09-01-00/resource-instance/user/signin
            # extraParams: <instance_size> <disk_size> <replica_count> <tls>
            extraParams: "e2-custom-4-10240 30 2 false"
          - name: PRO/MultiZone - GCP/us-central1 - Failover & Persistence
            testFile: test_multi_zone.py
            cloudProvider: gcp
            cloudRegion: us-central1
            subscriptionId: sub-GJPV3NoNC0
            apiPath: 2022-09-01-00/resource-instance/sp-JvkxkPhinN/falkordb-internal/v1/dev/falkordb-internal-customer-hosted/falkordb-internal-hosted-tier-falkordb-internal-customer-hosted-model-omnistrate-dedicated-tenancy/multi-Zone
            apiFailoverPath: 2022-09-01-00/resource-instance/sp-JvkxkPhinN/falkordb-internal/v1/dev/falkordb-internal-customer-hosted/falkordb-internal-hosted-tier-falkordb-internal-customer-hosted-model-omnistrate-dedicated-tenancy
            apiSignInPath: 2022-09-01-00/resource-instance/user/signin
            # extraParams: <instance_size> <disk_size> <replica_count> <tls>
            extraParams: "e2-custom-4-10240 30 2 false"
          - name: PRO/Standalone - GCP/us-central1 - Failover & Persistence With TLS
            testFile: test_standalone.py
            cloudProvider: gcp
            cloudRegion: us-central1
            subscriptionId: sub-GJPV3NoNC0
            apiPath: 2022-09-01-00/resource-instance/sp-JvkxkPhinN/falkordb-internal/v1/dev/falkordb-internal-customer-hosted/falkordb-internal-hosted-tier-falkordb-internal-customer-hosted-model-omnistrate-dedicated-tenancy/standalone
            apiFailoverPath: 2022-09-01-00/resource-instance/sp-JvkxkPhinN/falkordb-internal/v1/dev/falkordb-internal-customer-hosted/falkordb-internal-hosted-tier-falkordb-internal-customer-hosted-model-omnistrate-dedicated-tenancy/node-s
            apiSignInPath: 2022-09-01-00/resource-instance/user/signin
            # extraParams: <instance_size> <disk_size> <tls>
            extraParams: "e2-custom-4-10240 30 true"
          - name: PRO/SingleZone - GCP/us-central1 - Failover & Persistence With TLS
            testFile: test_single_zone.py
            cloudProvider: gcp
            cloudRegion: us-central1
            subscriptionId: sub-GJPV3NoNC0
            apiPath: 2022-09-01-00/resource-instance/sp-JvkxkPhinN/falkordb-internal/v1/dev/falkordb-internal-customer-hosted/falkordb-internal-hosted-tier-falkordb-internal-customer-hosted-model-omnistrate-dedicated-tenancy/single-Zone
            apiFailoverPath: 2022-09-01-00/resource-instance/sp-JvkxkPhinN/falkordb-internal/v1/dev/falkordb-internal-customer-hosted/falkordb-internal-hosted-tier-falkordb-internal-customer-hosted-model-omnistrate-dedicated-tenancy
            apiSignInPath: 2022-09-01-00/resource-instance/user/signin
            # extraParams: <instance_size> <disk_size> <replica_count> <tls>
            extraParams: "e2-custom-4-10240 30 2 true"
          - name:  PRO/MultiZone - GCP/us-central1 - Failover & Persistence With TLS
            testFile: test_multi_zone.py
            cloudProvider: gcp
            cloudRegion: us-central1
            subscriptionId: sub-GJPV3NoNC0
            apiPath: 2022-09-01-00/resource-instance/sp-JvkxkPhinN/falkordb-internal/v1/dev/falkordb-internal-customer-hosted/falkordb-internal-hosted-tier-falkordb-internal-customer-hosted-model-omnistrate-dedicated-tenancy/multi-Zone
            apiFailoverPath: 2022-09-01-00/resource-instance/sp-JvkxkPhinN/falkordb-internal/v1/dev/falkordb-internal-customer-hosted/falkordb-internal-hosted-tier-falkordb-internal-customer-hosted-model-omnistrate-dedicated-tenancy
            apiSignInPath: 2022-09-01-00/resource-instance/user/signin
            # extraParams: <instance_size> <disk_size> <replica_count> <tls>
            extraParams: "e2-custom-4-10240 30 2 true"
          - name: PRO/Standalone - GCP/us-central1 - Update Memory
            testFile: test_update_memory.py
            cloudProvider: gcp
            cloudRegion: us-central1
            subscriptionId: sub-GJPV3NoNC0
            apiPath: 2022-09-01-00/resource-instance/sp-JvkxkPhinN/falkordb-internal/v1/dev/falkordb-internal-customer-hosted/falkordb-internal-hosted-tier-falkordb-internal-customer-hosted-model-omnistrate-dedicated-tenancy/standalone
            apiSignInPath: 2022-09-01-00/resource-instance/user/signin
            # extraParams: <instance_size> <disk_size> <instance_type_new> <tls>
            extraParams: "e2-custom-4-10240 30 e2-custom-8-10240 false"
          - name: PRO/SingleZone - GCP/us-central1 - Update Memory
            testFile: test_update_memory.py
            cloudProvider: gcp
            cloudRegion: us-central1
            subscriptionId: sub-GJPV3NoNC0
            apiPath: 2022-09-01-00/resource-instance/sp-JvkxkPhinN/falkordb-internal/v1/dev/falkordb-internal-customer-hosted/falkordb-internal-hosted-tier-falkordb-internal-customer-hosted-model-omnistrate-dedicated-tenancy/single-Zone
            apiSignInPath: 2022-09-01-00/resource-instance/user/signin
            # extraParams: <instance_size> <disk_size> <instance_type_new> <tls>
            extraParams: "e2-custom-4-10240 30 e2-custom-8-10240 false"
     
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./tests/requirements.txt

      - name: ${{ matrix.instances.name }}
        env:
          CLOUD_PROVIDER: ${{ matrix.instances.cloudProvider }}
          CLOUD_REGION: ${{ matrix.instances.cloudRegion }}
          SUBSCRIPTION_ID: ${{ matrix.instances.subscriptionId }}
          API_VERSION: ${{ matrix.instances.apiVersion }}
          API_PATH: ${{ matrix.instances.apiPath }}
          API_FAILOVER_PATH: ${{ matrix.instances.apiFailoverPath }}
          API_SIGN_IN_PATH: ${{ matrix.instances.apiSignInPath }}
          extraParams: ${{ matrix.instances.extraParams }}
        run: |
          python ./tests/${{ matrix.instances.testFile }} ${{ secrets.OMNISTRATE_USERNAME }} ${{ secrets.OMNISTRATE_PASSWORD }} ${{ env.CLOUD_PROVIDER }} ${{ env.CLOUD_REGION }} ${{ env.extraParams }}
