name: Check TLS Certificate Expiry

on:
  schedule:
    - cron: '0 8 * * 1,4' # Every Monday and Thursday at 08:00 UTC
  workflow_dispatch:

jobs:
  check-tls:
    name: Check TLS Expiry and Alert
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: List Omnistrate Instances
        id: list_instances
        uses: ./.github/actions/list-omnistrate-instances
        with:
          username: ${{ secrets.OMNISTRATE_USERNAME }}
          password: ${{ secrets.OMNISTRATE_PASSWORD }}
          filter: service:FalkorDB,environment:Prod,status:RUNNING
          skipFreeTier: true

      - name: Filter TLS-enabled Instances and Check Expiry
        id: check_tls
        run: |
          echo '${{ steps.list_instances.outputs.instances }}' | jq -c '.[] | select(.tls == true)' > tls_instances.json

          alerts=()

          while IFS= read -r instance; do
            instance_id=$(echo "$instance" | jq -r '.instance_id')
            endpoint=$(echo "$instance" | jq -r '.endpoint')

            echo "Checking TLS for $endpoint"
            end_date=$(echo | openssl s_client -servername "$endpoint" -connect "$endpoint" 2>/dev/null \
              | openssl x509 -noout -enddate | cut -d= -f2)

            if [ -z "$end_date" ]; then
              echo "Could not retrieve cert for $endpoint"
              continue
            fi

            end_timestamp=$(date -d "$end_date" +%s)
            now=$(date +%s)
            days_left=$(( (end_timestamp - now) / 86400 ))

            echo "$endpoint expires in $days_left days"

            if [ "$days_left" -lt 15 ]; then
              curl -X POST 'https://events.pagerduty.com/v2/enqueue' \
                -H 'Content-Type: application/json' \
                -d "{
                  \"routing_key\": \"${{ secrets.PAGERDUTY_ROUTING_KEY }}\",
                  \"event_action\": \"trigger\",
                  \"payload\": {
                    \"summary\": \"TLS cert for $instance_id expires in $days_left days\",
                    \"source\": \"github-actions\",
                    \"severity\": \"warning\"
                  },
                  \"custom_details\": {
                    \"instance_id\": \"$instance_id\",
                    \"endpoint\": \"$endpoint\",
                    \"days_remaining\": \"$days_left\"
                  }
                }"
            fi
          done < tls_instances.json
