name: Check TLS Certificate Expiry

on:
  schedule:
    - cron: '0 8 * * 1,4' # Every Monday and Thursday at 08:00 UTC
  workflow_dispatch:

jobs:
  check-tls:
    name: Check TLS Expiry and Alert
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run TLS Certificate Expiration Check
        run: |
          poetry run python omnistrate_tests/test_tls_expiration.py \
            "${{ secrets.OMNISTRATE_USERNAME }}" \
            "${{ secrets.OMNISTRATE_PASSWORD }}" \
            "${{ secrets.PAGERDUTY_ROUTING_KEY }}" \
            "${{ vars.OMNISTRATE_INTERNAL_SERVICE_ID }}" \
            "${{ vars.OMNISTRATE_INTERNAL_PROD_ENVIRONMENT }}" \
            --verbose
        env:
          PYTHONPATH: ${{ github.workspace }}
