name: Delete Omnistrate Service Plan

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
  delete:

jobs:
  delete-service-plan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        plans:
          - tier-name: free-${{ github.event_name == 'pull_request' && github.base_ref || github.ref_name }}
          - tier-name: pro-${{ github.event_name == 'pull_request' && github.base_ref || github.ref_name }}
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Delete Service Plan
        uses: ./.github/actions/delete-omnistrate-service-plan
        continue-on-error: true
        with:
          username: ${{ secrets.OMNISTRATE_USERNAME }}
          password: ${{ secrets.OMNISTRATE_PASSWORD }}
          service-id: ${{ vars.OMNISTRATE_INTERNAL_SERVICE_ID }}
          environment-id: ${{ vars.OMNISTRATE_INTERNAL_DEV_ENVIRONMENT }}
          # The clsosed PR's ref name will be the product tier name
          product-tier-name: ${{ matrix.plans.tier-name }}
