name: Cleanup after PR

on:
  workflow_dispatch:
      inputs:
        ref-name: 
          description: 'The name of the branch or tag to delete'
          required: true
          default: 'main'
  pull_request:
    types: [closed]

env: 
  GCP_NETWORK_NAME: gcp-network-${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || inputs.ref-name }}
  AWS_NETWORK_NAME: aws-network-${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || inputs.ref-name }}

jobs:
  delete-networks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Delete Omnistrate Custom Network - GCP
        uses: ./.github/actions/delete-omnistrate-custom-network
        continue-on-error: true
        with:
          username: ${{ secrets.OMNISTRATE_USERNAME }}
          password: ${{ secrets.OMNISTRATE_PASSWORD }}
          custom_network_name: ${{ env.GCP_NETWORK_NAME }}

      - name: Delete Omnistrate Custom Network - AWS
        continue-on-error: true
        uses: ./.github/actions/delete-omnistrate-custom-network
        with:
          username: ${{ secrets.OMNISTRATE_USERNAME }}
          password: ${{ secrets.OMNISTRATE_PASSWORD }}
          custom_network_name: ${{ env.AWS_NETWORK_NAME }}

  delete-service-plan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        plans:
          - tier-name: free-${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref_name }}
          - tier-name: pro-${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Delete Service Plan
        uses: ./.github/actions/delete-omnistrate-service-plan
        continue-on-error: true
        with:
          username: ${{ secrets.OMNISTRATE_USERNAME }}
          password: ${{ secrets.OMNISTRATE_PASSWORD }}
          service-id: ${{ vars.OMNISTRATE_INTERNAL_SERVICE_ID }}
          environment-id: ${{ vars.OMNISTRATE_INTERNAL_DEV_ENVIRONMENT }}
          # The clsosed PR's ref name will be the product tier name
          product-tier-name: ${{ matrix.plans.tier-name }}
