name: Build Docker Image for testing
on:
  workflow_dispatch:

jobs:
  build_scan_container_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build multi-arch image
        uses: docker/build-push-action@v6
        with:
          context: ./operator/Dockerfile
          platforms: linux/arm64,linux/amd64
          push: false
          tags: falkordb/redis-operator-server:latest